<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-06-24T19:13:43 IST" name="Suite" finished-at="2025-06-24T19:13:51 IST" duration-ms="7879">
    <groups>
    </groups>
    <test started-at="2025-06-24T19:13:43 IST" name="Test" finished-at="2025-06-24T19:13:51 IST" duration-ms="7879">
      <class name="api.testcases.UserTest">
        <test-method is-config="true" signature="setupData()[pri:0, instance:api.testcases.UserTest@74235045]" started-at="2025-06-24T19:13:43 IST" name="setupData" finished-at="2025-06-24T19:13:43 IST" duration-ms="38" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupData -->
        <test-method signature="testGetUser()[pri:1, instance:api.testcases.UserTest@74235045]" started-at="2025-06-24T19:13:43 IST" name="testGetUser" finished-at="2025-06-24T19:13:46 IST" duration-ms="2680" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetUser -->
        <test-method signature="testUpdateUser()[pri:2, instance:api.testcases.UserTest@74235045]" started-at="2025-06-24T19:13:46 IST" name="testUpdateUser" finished-at="2025-06-24T19:13:48 IST" duration-ms="1895" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateUser -->
      </class> <!-- api.testcases.UserTest -->
      <class name="api.testcases.GroupTest">
        <test-method is-config="true" signature="setupData()[pri:0, instance:api.testcases.GroupTest@51399530]" started-at="2025-06-24T19:13:48 IST" name="setupData" finished-at="2025-06-24T19:13:48 IST" duration-ms="23" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupData -->
        <test-method signature="testCreateGroup()[pri:3, instance:api.testcases.GroupTest@51399530]" started-at="2025-06-24T19:13:48 IST" name="testCreateGroup" finished-at="2025-06-24T19:13:50 IST" duration-ms="1621" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [201] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [201] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.testcases.GroupTest.testCreateGroup(GroupTest.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateGroup -->
        <test-method signature="testGetGroupList()[pri:4, instance:api.testcases.GroupTest@51399530]" started-at="2025-06-24T19:13:50 IST" name="testGetGroupList" finished-at="2025-06-24T19:13:51 IST" duration-ms="1579" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetGroupList -->
      </class> <!-- api.testcases.GroupTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
